function main() {
    try {
        const user = getUser()
        // use user here
    } catch (err) {
        console.log(err)
    }
}